name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: publish

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Establish Version
        run: |
          release='${{ github.event.release.tag_name }}'
          version=`echo $release | cut -b2-`
          if ! echo $release | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$'; then
            echo "Release name must be in the format of 'vX.Y.Z[-anything]', got '$release'"
            exit 1
          fi
          sed -i -r "s/\"version\": *\".+\"/\"version\": \"$version\"/" package.json
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build Distributables
        run: yarn build
      - name: Publish to NPM
        run: |
          touch $HOME/.npmrc
          chmod 0600 $HOME/.npmrc
          cat << EOF > ~/.npmrc
          //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          EOF
          npm publish
        env:
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
