name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cypress-version: ["10", "11", "12"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install --immutable
      - run: yarn up cypress@${{ matrix.cypress-version }}
      - run: npm test
